### ISSUE TITLE
Issue #12 - How to model the priority of an actor in the production of an artefact?

### ISSUE THREAD

**Issue by chin-rcip** [chin-rcip/chin-rcip#12] opened 2019-10-31 15:59 UTC
In the v1.5 of the Target Model, the priority of the creator within the production event is modeled with the pattern:
`E39_Actor(creator)->P02i_is_ranged_of->PC14_Carried_out_by->P2_has_type->E55Type(Priority)->"Priority"`

Does the priority need to be linked to the PC14 Carried out by with a P2 has type, as it is now, or with the property P14.1 in the role of, just like the role of the actor?
`E39_Actor(creator)->P02i_is_ranged_of->PC14_Carried_out_by->P14.1_in_the_role_of->E55Type(Priority)->"Priority"`

Or should the priority be linked not to the PC14 Carried out by but to the role (E55 Type) with the property P2 has type, as follows:
`E39_Actor(creator)->P02i_is_ranged_of->PC14_Carried_out_by->P14.1_in_the_role_of->E55_Type(Role)->P2_has_type->E55Type(Priority)->"Priority"`

George Bruseker, in the Artefact Semantic Reference Data Model, modeled this priority linked to the PC14 with the Priority P14.1 in the role of.

**Comment by Habennin** [comment] 2019-11-10 16:43
If you put the type on the type then you are not qualifying the role at the moment but the role as such. So you would be saying that 'painter' is always 'first' for example. This would be semantically incorrect.

**Comment by stephenhart8** [comment] 2019-11-12 16:34
Indeed, therefore the only correct solution is number 2, with the property `P14.1 in the role of` and then the `E55 Type` for the priority.
I can close this issue unless there is something to add.

**Comment by Habennin** [comment] 2019-11-12 16:44
+1

**Comment by stephenhart8** [comment] 2019-11-14 20:26
The modifications has been made to the Target Model, the issue is closed.

**Comment by illip** [comment] 2019-11-14 20:28
It looks strange to me to use `PC14.1` for the priority but the definition of `p14.1` is quite broad (allows the nature of an actor's participation to be specified), so I'm fine with it :)

That said, if we use PC14.1 for the role and the priority I think we need a `e55->p2->e55` pattern to distinguish them.

So, +1

**Comment by stephenhart8** [comment] 2019-11-14 20:29
The modifications have been made to the Target Model, this issue is closed.

**Closed by stephenhart8** 2019-11-14 20:29 UTC
Labels: model

**Comment by VladimirAlexiev** [comment] 2020-03-31 17:02
@stephenhart8 @illip @Habennin This assumes "priority" is a concept.

But scholarly articles have a numeric author order.
That's why WD has prop https://www.wikidata.org/wiki/Property:P1545 "series ordinal".
Eg see how it's used for a paper: https://www.wikidata.org/wiki/Q58295578.

I assume the same holds about art publications such as exhibition catalogs, catalogs raisonne, etc
